### ISSUE TITLE
Add distro logo's in results page

### ISSUE THREAD

**Issue by fwsmit** [distrochooser/distrochooser#148]
In the results page, it would be nice to have logo's of the different distro's next to their name.

**Comment by cmllr** [comment]
The previous releases had distro images, but I decided to not include them in the newer version to make the lists more compact as they already consist out of a lot of elements. But as I'm collecting ideas for the next version, I will add this issue also on the idea list for the next version.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@cmllr, my opinion is that the current list is much more easy to parse because imagery is not present. Additionally, the logos are not useful for deciding which distribution is ideal/superior for the user of the service, so presence of them may cause more people to choose whichever distribution's logo is more visually pleasant, which would undermine the usefulness of this tool slightly.

**Comment by SirDK** [comment]
No. The current text information on the results page is as objective as possible. The logos are completely out of place.

**Comment by cmllr** [comment]
After an additional rethink I decided not to consider adding logos on the result page. I think the arguments of @BEEDELLROKEJULIANLOCKHART  and @SirDK are describing quite good why logos should be kept out of the result list.
