### ISSUE TITLE
Add Bedrock Linux to the list of available distributions

### ISSUE THREAD

**Issue by Epikest** [distrochooser/distrochooser#162]
https://bedrocklinux.org/

**Comment by paradigm** [comment]
I think it will be difficult to find a good set of questions for Bedrock Linux.  It's something of a pessimistic case for distrochooser's Q&A model.  If you expand the X-or-Y questions to include the naively obviously preferable "both" option I imagine it would recommend Bedrock too readily.  Even within the Bedrock community it's difficult to summarize whether Bedrock is suitable for someone; the usual recommendation is to try it out in a VM.

Additionally, Bedrock developers are actively seeking to _lessen_ attention, not broaden it.  Development is very slow because the limited available resources are consumed by the large support load.  Adding Bedrock to distrochooser will just exacerbate things.

Perhaps down the road when Bedrock is closer to a feature complete 1.0, when it's easier to determine whether Bedrock is suitable for someone and when fewer resources are needed for core development, it'll be better suited for distrochooser.  For now my preference would be against adding Bedrock to distrochooser.

**Comment by Epikest** [comment]
aren't you the creator of bedrock? you hold all the power then

**Comment by hacknorris-aka-penguin** [comment]
wait- thk for distro, one time tried to make lfs... (bookmarked)

**Comment by cmllr** [comment]
Actually, Bedrock was included in one of the previous versions, but as @paradigm alread mentioned, It's quite hard to add an distribution like bedrock. And with the current release of distrochooser, I tried to reduce the list of distros a bit to less confuse newbies.  Especially with the current question structure, I don't think I can add an decision tree definition offering a properly matching result for Bedrock.

Anyways, I added the tag for the next release so I can consider these aspects when doing the concept for the next version. I might pick up this dicussion at a later point, but I will close that for now. Thank you all for your input!

PS: @paradigm If you think Bedrock is ready at a later point, feel free to give me a ping so we can take a closer look then to add it!

**Comment by paradigm** [comment]
@cmllr 

> PS: @paradigm If you think Bedrock is ready at a later point, feel free to give me a ping so we can take a closer look then to add it!

While I appreciate your welcomeness here, I'm not sure what you mean by ready.  The difficulty as I understand it is not about some area Bedrock needs to improve such that it could later be ready.  Rather, it's about a fundamental weirdness that makes it difficult to fit into distrochooser's model, and that isn't something which is likely to change such that Bedrock would later be ready.

I am working toward Bedrock Linux 0.8 which should be a substantial improvement over the current version.  If we're looking for an arbitrary date to revisit Bedrock, the future 0.8 release is about as fine a Schelling point as anything else.  However, AFAIK the current 0.7 is perfectly serviceable for Bedrock's target audience, and there's no item of improvement in particular that would make 0.8 or anything else on Bedrock's roadmap better suited for distrochooser's needs.

**Comment by cmllr** [comment]
thanks for the remark @paradigm. What do you mean with "fundamendtal weirdness"?

**Comment by paradigm** [comment]
Bedrock Linux is [a meta Linux distribution](https://bedrocklinux.org/faq.html#what-is-meta) made up of parts of other distros.  Bedrock's core code is essentially glue that forces/tricks normally incompatible parts of other distros to work together.  It doesn't run on top of another distro, but is pervasive to a Bedrock system; _every_ part can be swapped out with corresponding bits from other distros except the Bedrock code itself that glues the system together.  You can use one distro's installer, another distro's kernel, a third distro's init; you can download a PDF with a web browser from one distro and open the PDF with a PDF reader from another; one distro's `man` can read another distro's man page; etc.  Bedrock is normally categorized along side traditional distros because if you're running a mix of parts of other distros where you can swap out anything except the Bedrock bits that glue the system together, Bedrock is the only defining part of the system.  If someone asks me what distro I'm running, "Bedrock Linux" and "it's complicated" are the only two reasonable answers.

This is very weird and different from traditional distros.  Consequently, it's difficult to find a reasonable set of questions that reasonably divide up the Linux distro ecosystem which also reasonably cover Bedrock.  Since Bedrock can get the corresponding features from other distros which offer them, Bedrock essentially ticks "all of the above" for the majority of distrochooser's questions.  If care isn't taken to do something about it, distrochooser may end up over-recommending Bedrock as it checks so many boxes.  If one tries to compensate by adding in Bedrock-specific questions, then distrochooser loses a lot of its value as a quick general way to narrow things down; at that rate you may as well go through things distro-by-distro.

The only way I see to resolve this is to leave Bedrock out of distrochooser's considerations.  I don't think that ends up being a loss for either distrochooser or Bedrock, though.  Consider: distrochooser's target audience is those that don't have experience with a variety of Linux distros.  Bedrock's target audience is the exact opposite; to really leverage Bedrock, you need background in a variety different Linux distros.  Consequently, if someone goes to distrowatch we can assume a priori Bedrock likely isn't a great choice for them.
