### ISSUE TITLE
[Suggestion] distrochooser is the solution for distrohopping?

### ISSUE THREAD

**Issue by ghost** [distrochooser/distrochooser#196]
**Is your feature request related to a problem? Please describe.**
I believe that distrochooser can be a viable option to solve common doubts when choosing a distro whether by advanced, intermediate or beginner users. For example, there are several problems in linux like: "fragmentation", "distrohopping" etc. In this feature request, I ask more technical questions to solve distrohopping. 

**Describe the solution you'd like**
A solution to solve this problem(distrohopping) is to evaluate the distro according to the technical need. For example, doubts about whether the user has experience in Linux, can help when choosing a distro. Or... another example, doubts whether the user knows any distro, and wants to use a distro similar to the previous distro that has experience in use, can help when choosing a new distro.

**Describe alternatives you've considered**
*Here's a series of technical questions that depending on the answer may lead to more technical questions. Questions are not in chronological order, questions appear depending on previous answers.*

> do you have experience with linux? (yes|no)
|> next step.

> have you already used the ubuntu distro and want a similar distro? (yes|no)
|> next step, example(option): Manjaro, Debian ...

> what is your degree of knowledge in linux?
|> advanced?  (more technical questions)
|> intermediary? (advanced questions)
|> basic? (basic questions)

> do you have knowledge in computer programming? (yes|no)
|> next step.

> have you ever taken a computer programming course? (yes|no)
|> next step.

> are you certified in linux? (yes|no)
|> next step.

> do you work with software development? (yes|no)
|> next step.

> do you know software licenses? (yes|no)
|> next step.

> are you looking for a linux distro that has bootloader support? (yes|no)
|> GRUB. (show this is option)
|> rEFInd (show this is option)
|> lilo (show this is option)
|> burg (show this is option)
|> systemd-boot etc. (show this is option)
|> next step.

> are you looking for a linux distro that has display render support? (yes|no)
|> Xorg. (show this is option)
|> gammastep. (show this is option)
|> Redshift. (show this is option)
|> Wayland. (show this is option)
|> [Ncurses](https://en.wikipedia.org/wiki/Ncurses). (show this is option)
|> [Mir](https://alternativeto.net/software/mir/about/) etc. (show this is option)
|> [rio](https://en.m.wikipedia.org/wiki/Rio_(windowing_system)) etc. (show this is option)
|> Synergy/barrier. (show this is option)
|> next step.

> do you want a linux distro without systemd? (yes|no)
|> Devuan (show this is option)
|> AntiX (show this is option)
|> MX Linux (show this is option)
|> Nitrux (show this is option)
|> Void Linux (show this is option)
|> GoboLinux (show this is option)
|> Alpine Linux (show this is option)
|> Artix (show this is option)
|> TinyCore Linux (show this is option)
|> Chimera Linux (show this is option)
|> Venom Linux (show this is option)
|> Kiss Linux (show this is option)
|> PCLinuxOS (show this is option)
|> Slackware (show this is option)
|> next step. 
 
> are you looking for a linux distro that has init system support? (yes|no)
|> System V (SysV) (show this is option)
|> Elogind (show this is option)
|> Upstart (show this is option)
|> OpenRC (show this is option)
|> runit (show this is option)
|> systemd. (show this is option)
|> next step.

> are you looking for a linux distro that has display manager support? (yes|no)
|> lightdm. (show this is option)
|> sddm. (show this is option)
|> gdm. (show this is option)
|> next step.

**Additional context**
Often the term distrohopping has 2 meanings: 
   - **1** meaning of searching for a linux distro that is the best of all or that solves all personal problems(meaning of the lack of one good distro)
   - **2** meaning of hobby(meaning of testing new linux distros)

**Comment by cmllr** [comment]
Distrochooser is, at first, an orientation guide for newbies. Secondary, it can help to reorientate while switching an distribution. For this, I'd like to keep the questions simple. I think in the future there might be *some* extension to the questionaire itself, but before Distrochooser can help more specific with distrohopping I think https://github.com/distrochooser/distrochooser/issues/149 needs to be implemented first to add some "reactivity" to the user's given answers.

I marked this issue with the version-6 label to have it considered when working on the next version.

**Comment by cmllr** [comment]
Just to give an update/ feedback to the mentioned issues:

#231 is currently only roughly drawn, is still a bit generic 
#230 see especially the comment https://github.com/distrochooser/distrochooser/issues/230#issuecomment-1439548673
#221 still needs more adaption to allow a proper comparison between fast and slow
#200 requires a lot of updates to properly display data, still a large WIP
#217 will focus on the selection of the subtopics (e.g. license -> GPL, MIT)

**Comment by cmllr** [comment]
For #220 I did some research on identifying Operating Systems and hardware. The majority of information I can extract from the browser is the user Agent besides some minor information about some hardware layers (which identify slightly different between windows and linux for example, mostly for memory and graphics). The issue here is that OS identifying information is not a standard on all browsers so some browser give these information, while in other browser they just do not exist.

I don't see major implications on the User Agent as the user agent identifies mostly build information, which are not that unique. A user still can choose not to publish any user agent, this is supported on most of the browsers if I remember correctly.

From a website perspective I can only do assumptions about the user platform, but I cannot be sure about the information given by the browser. Additionally, I often can only identify the family of OS'es from these information, not the distribution.

**Comment by eflixandrols** [comment]
Some interesting technical questions
- Swap support	
- Encryption support	
- Secure Boot support	
- Nvidia proprietary driver support
- Linux-surface patches support	
- ready booster usb

**Comment by marcelolucario** [comment]
I would like to contribute to this issue here. I would like to solve all the technical issue of linux here. A general idea I have would be to observe certain characteristics.

>
> do you want a linux distro with alternative systemd? (yes|no)
|> dinit. (show this is option)
|> s6. (show this is option)
>
>
> do you want a linux distro without systemd? (yes|no)
|> Devuan. (show this is option)
|> AntiX. (show this is option)
|> MX Linux. (show this is option)
|> Nitrux. (show this is option)
|> Void Linux. (show this is option)
|> GoboLinux. (show this is option)
|> Alpine Linux. (show this is option)
|> Artix. (show this is option)
|> TinyCore Linux. (show this is option)
|> Chimera Linux. (show this is option)
|> Venom Linux. (show this is option)
|> Kiss Linux. (show this is option)
|> PCLinuxOS. (show this is option)
|> Slackware. (show this is option)
|> next step.
>
>
> are you looking for a linux distro that has display render/server support? (yes|no)
|> Xorg. (show this is option)
|> gammastep. (show this is option)
|> Redshift. (show this is option)
|> Wayland. (show this is option)
|> Ncurses. (show this is option)
|> Mir. (show this is option)
|> rio. (show this is option)
|> Synergy/barrier. (show this is option)
|> MicroXWin. (show this is option)
|> Y. (show this is option)
|> DFB. (show this is option)
|> Xynth Window System. (show this is option)
|> Fresco. (show this is option)
|> Y Window System. (show this is option)
|> Metisse. (show this is option)
|> DirectFB. (show this is option)
|> KDrive (or TinyX, Tiny X). (show this is option)
|> Syllable Server. (show this is option)
|> Yutani. (show this is option)
|> Compiz. (show this is option)
|> Xquartz. (show this is option)
|> Xming. (show this is option)
|> Xenocara. (show this is option)
|> OpenVMS. (show this is option)
|> next step.
>
>
> are you looking for a linux distro that has feature support? (yes|no)
|> Swap. (show this is option)
|> Encryption. (show this is option)
|> Secure Boot. (show this is option)
|> Nvidia proprietary driver. (show this is option)
|> Linux-surface patches. (show this is option)
|> Ready Booter usb. (show this is option)
>
>
> are you looking for a linux distro that has graphic render support? (yes|no)
|> Vulkan. (show this is option)
|> DirectX. (show this is option)
|> Metal. (show this is option)
|> OpenGL. (show this is option)
|> WebGPU. (show this is option)
|> next step.
>
>
> are you looking for a linux distro that has window manager support? (yes|no)
|> Kwin. (show this is option)
|------|> KDE
|> Mutter. (show this is option)
|------|> GNOME
|> XFwm. (show this is option)
|------|> none
|> Muffin. (show this is option)
|------|> Cinnamon desktop
|> next step.
>
> are you looking for a linux distro that has display manager support? (yes|no)
|> Gdm. (show this is option)
|> KDM. (show this is option)
|> Lightdm. (show this is option)
|> next step.
>
> are you looking for a linux distro that has hardware architeture support? (yes|no)
|> x86. (show this is option)
|> MIPS. (show this is option)
|> DEC. (show this is option)
|> SPARC. (show this is option)
|> PowerPC. (show this is option)
|> ARM. (show this is option)
|> Alpha. (show this is option)
|> i486. (show this is option)
|> next step.
>
> are you looking for a linux distro that has DPI support? (yes|no)
|> 160 DPI. (show this is option)
|> 300 DPI. (show this is option)
|> 200 DPI. (show this is option)
|> 1000 DPI+-. (show this is option)
|> next step.
>
> are you looking for a linux distro that has kernel architeture support? (yes|no)
|> Microkernel. (show this is option)
|> Nanokernel. (show this is option)
|> Safe-language SAS/SPL-OS or SPLOS. (show this is option)
|> Monolithic Kernel. (show this is option)
|> next step.
>
> are you looking for a linux distro that has filesystem support? (yes|no)
|> ext2. (show this is option)
|> ext3. (show this is option)
|> ReiserFS. (show this is option)
|> Fat12. (show this is option)
|> Fat16. (show this is option)
|> Fat32. (show this is option)
|> NTFS. (show this is option)
|> ZFS. (show this is option)
|> ISO9660. (show this is option)
|> MFS. (show this is option)
|> next step.
>
> are you looking for a linux distro that has filesystem support with journaling? (yes|no)
|> ext3. (show this is option)
|> ReiserFS. (show this is option)
|> next step.
>
> are you looking for a linux distro that has filesystem support without journaling? (yes|no)
|> ext2. (show this is option)
|> Fat12. (show this is option)
|> Fat16. (show this is option)
|> Fat32. (show this is option)
|> NTFS. (show this is option)
|> ZFS. (show this is option)
|> ISO9660. (show this is option)
|> MFS. (show this is option)
|> next step.
>
>
> are you looking for a linux distro that has purpose support? (yes|no)
|> General purpose. (show this is option)
|> General embedded. (show this is option)
|> PoC. (show this is option)
|> Embedded Devices. (show this is option)
|> next step.

**Comment by gorlask** [comment]
Hi everyone, I forgot to complete the list of technical questions.

> which linux distro has support for this version of graphics render or apis graphics?
|> DirectX 2.0a
|> DirectX 0-12x. (show this is option)
|> next step.
> 
>
> are you looking for a linux distro that has hardware architeture support? (yes|no)
|> x86. (show this is option)
|> MIPS. (show this is option)
|> DEC. (show this is option)
|> SPARC. (show this is option)
|> PowerPC. (show this is option)
|> ARM. (show this is option)
|> Alpha. (show this is option)
|> i486. (show this is option)
|> IBM power. (show this is option)
|> IBM Z. (show this is option)
|> IBM LinuxONE. (show this is option)
|> next step.
